const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

module.exports = require('./webpack.base')({
  mode: 'development',

  entry: path.join(process.cwd(), 'src/app'),

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },

  // Add development plugins
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      // By default, this plugin will inject all files that are generated by webpack, e.g. bundle.js
      // See https://github.com/jantimon/html-webpack-plugin#options
      inject: true,
    }),

    new ReactRefreshWebpackPlugin(),
  ],

  performance: {
    hints: false,
  },

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',
});
